dist: trusty
sudo: false
notifications:
  email: false
language: node_js
node_js:
  - "8"
  - "6"
  - "4"
cache:
  directories:
    - node_modules
script:
  - "npm test"
jobs:
  include:
    - stage: lint and npm release
      node_js: "8"
      script:
        - npm run lint
      after_success:
        - npm run semantic-release
branches:
  only:
    - master
